### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by hoodz123** [Dhruvpamnani/money-wash-qb-target#1]
so it lets me put the marked bills it but dont wash say nothing to wash check items to make sure everythings a match buut still nothing no errors just bring up the stash but dont start the wash

**Comment by Dhruvpamnani** [comment]
> so it lets me put the marked bills it but dont wash say nothing to wash check items to make sure everythings a match buut still nothing no errors just bring up the stash but dont start the wash

its a fork of the resource and i think there is sql issue
